name: Pipeline

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master

jobs:
  install-test-build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          # Ensure Python 3.8 matches everywhere.
          python-version: 3.8

      - name: Install
        run: |
          python --version
          pip install . --upgrade
          pip install -r authelio_sdk_tests/requirements.txt
          pip list

      - name: Test
        run: |
          export AUTHENA_PUBLIC_API_URL="${{ secrets.AUTHENA_PUBLIC_API_URL }}"
          export AUTHENA_API_KEY="${{ secrets.AUTHENA_API_KEY }}"
          export AUTHENA_API_SECRET="${{ secrets.AUTHENA_API_SECRET }}"
          pytest authelio_sdk_tests

      - name: Install
        run: pip install wheel twine

      - name: Build
        run: python setup.py sdist bdist_wheel

      - name: Upload
        run: twine upload dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
